name: Integration Tests
on:
    push:
        branches:
            - "*"
    pull_request:
        branches:
            - "*"

jobs:
    integration-tests:
        runs-on: ubuntu-latest
        env:
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        steps:
            - uses: actions/checkout@v4

            - uses: pnpm/action-setup@v3
              with:
                  version: 9.15.0

            - uses: actions/setup-node@v4
              with:
                  node-version: "23.3.0"
                  cache: 'pnpm'
                  cache-dependency-path: '**/pnpm-lock.yaml'

            - name: Configure pnpm
              run: |
                  pnpm config set store-dir ~/.pnpm-store
                  pnpm config set prefer-offline true
                  pnpm config set node-linker hoisted
                  pnpm config set shamefully-hoist true
                  pnpm config list

            - name: Install dependencies
              run: pnpm install -r --no-frozen-lockfile --prefer-offline

            - name: Build packages
              run: pnpm build

            - name: Run integration tests
              env:
                  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
                  COINBASE_COMMERCE_KEY: ${{ secrets.COINBASE_COMMERCE_KEY }}
              run: |
                  pnpm run integrationTests
